name: Atividade 2

on:
  workflow_dispatch:
  push:
    paths:
      - atividade-2/**
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PICO_SDK_PATH: ~/pico/pico-sdk
      SDK_VERSION: 1.5.0
    steps:
      - uses: actions/checkout@v3
      - name: Cache Pico SDK
        id: cache-pico-sdk
        uses: actions/cache@v3
        with:
          path: ~/pico
          key: ${{ runner.os }}-pico-sdk-${{ env.SDK_VERSION }}
      - name: Set up the toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential
      - name: Set up the Pi Pico SDK
        if: steps.cache-pico-sdk.outputs.cache-hit != 'true'
        run: |
          mkdir ~/pico
          cd ~/pico
          git clone https://github.com/raspberrypi/pico-sdk.git --depth 1 --branch ${SDK_VERSION}
          cd pico-sdk && git submodule update --init && cd ..
      - name: Compile firmware
        run: |
          cd ${{ github.workspace }}/atividade-2
          mkdir build
          cd build
          cmake ..
          make
      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: atividade-2/build/main.*

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Download firmware
        uses: actions/download-artifact@v2
        with:
          name: firmware
          path: atividade-2/build
      - name: Test Pi Pico SDK on Wokwi
        uses: wokwi/wokwi-ci-action@v1
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          path: atividade-2/test
          scenario: scenario.yml
